cancel job

diff --git a/.github/workflows/input-test2.yml b/.github/workflows/input-test2.yml
--- a/.github/workflows/input-test2.yml
+++ b/.github/workflows/input-test2.yml
@@ -29,7 +29,7 @@ jobs:
       - name: Set Output
         id: setOutput
         run: |
-              if [${{ steps.determineCluster.outputs.cluster }} == 'Unknown' ]; then echo "Cluster could not be determined!" && exit 1; fi
+              if [${{ steps.determineCluster.outputs.cluster }} == Unknown ]; then echo "Cluster could not be determined!" && exit 1; fi
               echo "result=${{ steps.determineCluster.outputs.cluster }}" >>  $GITHUB_OUTPUT
       
   OutputCluster:
