cancel job

diff --git a/.github/workflows/input-test2.yml b/.github/workflows/input-test2.yml
--- a/.github/workflows/input-test2.yml
+++ b/.github/workflows/input-test2.yml
@@ -28,7 +28,9 @@ jobs:
           environment: ${{ inputs.stream }}
       - name: Set Output
         id: setOutput
-        run: echo "result=${{ steps.determineCluster.outputs.cluster }}" >>  $GITHUB_OUTPUT
+        run: |
+              if [${{ steps.determineCluster.outputs.cluster }} == 'Unknown' ]; then echo "Cluster could not be determined!" && exit 1; fi
+              echo "result=${{ steps.determineCluster.outputs.cluster }}" >>  $GITHUB_OUTPUT
       
   OutputCluster:
     needs: DetermineCluster
